# Generated by Django 2.2 on 2019-04-20 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='internprofile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=30)),
                ('password', models.CharField(default='', max_length=30)),
                ('full_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=10)),
                ('profile_picture', models.ImageField(upload_to='profile_img')),
                ('document_file', models.FileField(upload_to='document_img')),
                ('stipend', models.CharField(max_length=10)),
                ('date_of_joining', models.DateField()),
                ('date_of_leaving', models.DateField()),
                ('internship_admin_remark', models.TextField()),
                ('internship_status', models.CharField(choices=[('Active', 'Active'), ('InActive', 'InActive')], max_length=128)),
            ],
            options={
                'verbose_name': 'Internprofile',
                'verbose_name_plural': 'Internprofiles',
            },
        ),
    ]
